import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import OverView from "../components/OverView";
import TopCountry from "../components/TopCountry";
import LineChart from "../components/LineChart";
import World from "../components/World";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CovidTracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <OverView />
        <World />
        <TopCountry />
        <LineChart />
      </main>
    </div>
  );
}
